apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-backend
  labels:
    {{- include "wordpress-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
