apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-backend
  labels:
    {{- include "wordpress-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "wordpress-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
