apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-frontend
  labels:
    {{- include "wordpress-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "wordpress-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
