apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: wordpress
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.wordpress.persistence.accessMode }}
  {{- if .Values.wordpress.persistence.storageClass }}
  storageClassName: {{ .Values.wordpress.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}
