apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
  labels:
    app: wordpress
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: wordpress
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: {{ .Values.wordpress.service.targetPort }}
      protocol: TCP
      name: http
  type: {{ .Values.wordpress.service.type }}
