apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: store-manual-test
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  # This exposes the service externally
  type: LoadBalancer